### ISSUE TITLE
Types broken in latest release

### ISSUE THREAD

**Issue by thewilkybarkid** [Bikossor/anonymus#111]
It looks like it's been fixed, but the types available in the latest release (`2.1.0`) are broken (TypeScript complains with a '... is not a module' error).

Is it possible to release a new patch version with the fix?

**Comment by Bikossor** [comment]
I'm looking into it

**Comment by Bikossor** [comment]
@thewilkybarkid can you provide an example where TypeScript complains?

**Comment by thewilkybarkid** [comment]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwHYSQTxAVwM5wGZQQhwBEyqGOJA3AFC3npbYB0AxlAKYIycAUASlpA

`anonymus.d.ts` looks like:

```ts
declare var anonymus: {
    // [...]
    create: (amount: any) => any[];
};
```

Looking at https://github.com/Bikossor/anonymus/blob/9a6c0c966372191d14e06f744969941597bd364e/src/anonymus.ts#L273-L275 there's a conditional export so the TypeScript compiler doesn't generate a valid module definition (i.e. there's no `export = anonymus`).

I see that there have been commits to change the library to use ESM, and `develop` does currently generate a valid definition file.

**Comment by Bikossor** [comment]
Yeah I think the problem is that develop has not been released since then 😅

**Comment by Bikossor** [comment]
I released a new version [2.1.1](https://github.com/Bikossor/anonymus/releases/tag/2.1.1)

Let me know if this works for you 😄

**Comment by thewilkybarkid** [comment]
Thanks! The types look right, but `main` in `package.json` refers to `anonymus.min.js` but it just seems to be called `anonymus.js`...

**Comment by Bikossor** [comment]
I've noticed that mismatch too. There are other things too that aren't quite right yet. This was caused by the structural changes I did lately. I'll try to fix it all up asap. Thank you very much for reporting these issues 😄
